#!/bin/bash
# Copyright 2018  Simon Arlott
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

umask 0077
if [ $# -ne 2 ]; then
	echo "Usage: $0 <linux socket path> <windows socket path>"
	exit 1
fi
if [ "$1" == "-" ] && [ "$2" == "-" ] && [ ! -z "$WSL_ASSUAN_UNIX_PROXY_TARGET" ]; then
	DATA=$(xxd -ps "$WSL_ASSUAN_UNIX_PROXY_TARGET")
	PORT=$(echo "$DATA" | sed -e 's/^\(\(3.\)\+\)0a\(.\+\)$/\1/' | xxd -ps -r)
	TOKEN=$(echo "$DATA" | sed -e 's/^\(\(3.\)\+\)0a\(.\+\)$/\3/')
	exec socat tcp-connect:127.0.0.1:"$PORT" stdio < <(echo "$TOKEN" | xxd -ps -r; cat)
else
	rm -f "$1"
	trap "break" SIGINT SIGTERM
	while true; do
		WSL_ASSUAN_UNIX_PROXY_TARGET="$2" socat unix-listen:"$1" exec:"$0 - -"
	done
	exit 0
fi
